# frozen_string_literal: true

require 'fileutils'
require 'open3'

module SousChefsStats
  # Runs oss-stats in GitHub-only mode over the dynamic inventory.
  class RepoReport
    def initialize(root:, runner: Open3)
      @root = root
      @runner = runner
    end

    def generate(date:, repositories:, token:)
      config_path = File.join(@root, 'tmp', "repo_stats_config-#{date}.rb")
      FileUtils.mkdir_p(File.dirname(config_path))
      File.write(config_path, config_for(repositories))

      stdout, stderr, status = @runner.capture3(
        { 'GITHUB_TOKEN' => token, 'GH_TOKEN' => token },
        'bundle', 'exec', 'repo_stats', '--config', config_path,
        '--mode', 'pr,issue,ci', chdir: @root
      )
      unless status.success?
        raise "oss-stats failed: #{stderr.strip.empty? ? stdout.strip : stderr.strip}"
      end
      raise 'oss-stats produced no repository report output' if stdout.strip.empty?

      warn stderr unless stderr.strip.empty?

      <<~MARKDOWN
        # Sous-Chefs Weekly Repository Stats - #{date}

        Generated by `oss-stats` using the live GitHub API inventory. Buildkite is intentionally excluded.
        Inventory coverage: #{repositories.length} active public non-fork repositories.

        #{stdout.strip}
      MARKDOWN
    end

    private

    def config_for(repositories)
      repo_config = repositories.to_h do |repo|
        [repo.fetch('name'), { 'branches' => [repo.fetch('default_branch')] }]
      end
      <<~RUBY
        default_days 7
        default_branches %w[main]
        include_list false
        count_unmerged_prs false
        log_level :info
        ci_timeout 600
        organizations(
          {
            'sous-chefs' => {
              'repositories' => #{repo_config.inspect},
            },
          },
        )
      RUBY
    end
  end
end
